# Generated by Django 2.1.2 on 2019-09-17 20:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled?')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time that this object was created.', verbose_name='Date object created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date object last modified')),
                ('url', models.CharField(db_index=True, help_text='The relative url path describing what page this model represents.e.g. /about/', max_length=255, unique=True, verbose_name='URL')),
                ('title', models.CharField(help_text='The page title', max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='The content to be displayed on the static page.', null=True, verbose_name='Content')),
                ('template_name', models.CharField(blank=True, help_text='The relative path describing which template to use. If not set will default to /staticpages/page.html', max_length=255, null=True, verbose_name='Template name')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
