"""Initial migrations for the Blog app, creating the blog post model."""
# Generated by Django 2.2.5 on 2019-11-28 16:52

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Blog post migration class."""

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled?')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time that this object was created.', verbose_name='Date object created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date object last modified')),
                ('title', models.CharField(help_text='Title of the blog post.', max_length=255, verbose_name='Title')),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Content of the blog post.', null=True, verbose_name='Content')),
                ('slug', models.SlugField(blank=True, default=None, help_text='URL slug of the blog post.', max_length=255, null=True, unique=True, verbose_name='Slug')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0, help_text='The status of the blog post.', verbose_name='Status')),
                ('published', models.DateTimeField(blank=True, help_text='Date blog post published.', null=True, verbose_name='Published')),
                ('author', models.ForeignKey(blank=True, help_text='The author of this blog post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog post',
                'verbose_name_plural': 'Blog posts',
            },
        ),
    ]
