"""
:synopsis: initial migrations for the authentication app.

Generated by Django 2.1.2 on 2018-10-10 19:23
.. module: authentication.migrations.0001
.. author: Chris Bartlett <bartlett.christopher.p@gmail.com>
"""

from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration."""

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True, verbose_name='Email address')),
                ('title', models.CharField(blank=True, db_index=True, default='', max_length=30, null=True, verbose_name='Title')),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Last name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
