# Generated by Django 2.2.5 on 2019-10-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time that this object was created.', verbose_name='Date object created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Date object last modified')),
                ('name', models.CharField(help_text='The name supplied by the enquiring user.', max_length=255, verbose_name='Name')),
                ('email', models.EmailField(help_text='The email address supplied by the enquiring user.', max_length=254, verbose_name='Email address')),
                ('message', models.TextField(help_text='The user enquiry.', verbose_name='Message')),
                ('resolved', models.BooleanField(default=False, help_text='Indicates if this enquiry has been resolved.', verbose_name='Enquiry resolved?')),
                ('notes', models.TextField(blank=True, help_text='Notes for administrators.', null=True, verbose_name='Administration notes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
